// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*_CoreCrtNonSecureSearchSortCompareFunction)(void*,void*);
 * }
 */
public interface _CoreCrtNonSecureSearchSortCompareFunction {

    int apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _x1);
    static MemorySegment allocate(_CoreCrtNonSecureSearchSortCompareFunction fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$63._CoreCrtNonSecureSearchSortCompareFunction_UP$MH, fi, constants$63._CoreCrtNonSecureSearchSortCompareFunction$FUNC, scope);
    }
    static _CoreCrtNonSecureSearchSortCompareFunction ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __x1) -> {
            try {
                return (int)constants$63._CoreCrtNonSecureSearchSortCompareFunction_DOWN$MH.invokeExact(symbol, __x0, __x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


