// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*at_quick_exit$x0)();
 * }
 */
public interface at_quick_exit$x0 {

    void apply();
    static MemorySegment allocate(at_quick_exit$x0 fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$75.at_quick_exit$x0_UP$MH, fi, constants$75.at_quick_exit$x0$FUNC, scope);
    }
    static at_quick_exit$x0 ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return () -> {
            try {
                constants$75.at_quick_exit$x0_DOWN$MH.invokeExact(symbol);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


