// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct AVClass {
 *     char* class_name;
 *     char* (*item_name)(void*);
 *     struct AVOption* option;
 *     int version;
 *     int log_level_offset_offset;
 *     int parent_log_context_offset;
 *     AVClassCategory category;
 *     AVClassCategory (*get_category)(void*);
 *     int (*query_ranges)(struct AVOptionRanges**,void*,char*,int);
 *     void* (*child_next)(void*,void*);
 *     struct AVClass* (*child_class_iterate)(void**);
 * };
 * }
 */
public class AVClass {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("class_name"),
        Constants$root.C_POINTER$LAYOUT.withName("item_name"),
        Constants$root.C_POINTER$LAYOUT.withName("option"),
        Constants$root.C_LONG$LAYOUT.withName("version"),
        Constants$root.C_LONG$LAYOUT.withName("log_level_offset_offset"),
        Constants$root.C_LONG$LAYOUT.withName("parent_log_context_offset"),
        Constants$root.C_LONG$LAYOUT.withName("category"),
        Constants$root.C_POINTER$LAYOUT.withName("get_category"),
        Constants$root.C_POINTER$LAYOUT.withName("query_ranges"),
        Constants$root.C_POINTER$LAYOUT.withName("child_next"),
        Constants$root.C_POINTER$LAYOUT.withName("child_class_iterate")
    ).withName("AVClass");
    public static MemoryLayout $LAYOUT() {
        return AVClass.$struct$LAYOUT;
    }
    static final VarHandle class_name$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("class_name"));
    public static VarHandle class_name$VH() {
        return AVClass.class_name$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* class_name;
     * }
     */
    public static MemorySegment class_name$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)AVClass.class_name$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* class_name;
     * }
     */
    public static void class_name$set(MemorySegment seg, MemorySegment x) {
        AVClass.class_name$VH.set(seg, x);
    }
    public static MemorySegment class_name$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)AVClass.class_name$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void class_name$set(MemorySegment seg, long index, MemorySegment x) {
        AVClass.class_name$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final FunctionDescriptor item_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor item_name_UP$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle item_name_UP$MH = RuntimeHelper.upcallHandle(item_name.class, "apply", AVClass.item_name_UP$FUNC);
    static final FunctionDescriptor item_name_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle item_name_DOWN$MH = RuntimeHelper.downcallHandle(
        AVClass.item_name_DOWN$FUNC
    );
    /**
     * {@snippet :
 * char* (*item_name)(void*);
     * }
     */
    public interface item_name {

        java.lang.foreign.MemorySegment apply(java.lang.foreign.MemorySegment _x0);
        static MemorySegment allocate(item_name fi, SegmentScope scope) {
            return RuntimeHelper.upcallStub(AVClass.item_name_UP$MH, fi, AVClass.item_name$FUNC, scope);
        }
        static item_name ofAddress(MemorySegment addr, SegmentScope scope) {
            MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
            return (java.lang.foreign.MemorySegment __x0) -> {
                try {
                    return (java.lang.foreign.MemorySegment)AVClass.item_name_DOWN$MH.invokeExact(symbol, __x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle item_name$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("item_name"));
    public static VarHandle item_name$VH() {
        return AVClass.item_name$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* (*item_name)(void*);
     * }
     */
    public static MemorySegment item_name$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)AVClass.item_name$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* (*item_name)(void*);
     * }
     */
    public static void item_name$set(MemorySegment seg, MemorySegment x) {
        AVClass.item_name$VH.set(seg, x);
    }
    public static MemorySegment item_name$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)AVClass.item_name$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void item_name$set(MemorySegment seg, long index, MemorySegment x) {
        AVClass.item_name$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static item_name item_name(MemorySegment segment, SegmentScope scope) {
        return item_name.ofAddress(item_name$get(segment), scope);
    }
    static final VarHandle option$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("option"));
    public static VarHandle option$VH() {
        return AVClass.option$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct AVOption* option;
     * }
     */
    public static MemorySegment option$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)AVClass.option$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct AVOption* option;
     * }
     */
    public static void option$set(MemorySegment seg, MemorySegment x) {
        AVClass.option$VH.set(seg, x);
    }
    public static MemorySegment option$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)AVClass.option$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void option$set(MemorySegment seg, long index, MemorySegment x) {
        AVClass.option$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle version$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("version"));
    public static VarHandle version$VH() {
        return AVClass.version$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int version;
     * }
     */
    public static int version$get(MemorySegment seg) {
        return (int)AVClass.version$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int version;
     * }
     */
    public static void version$set(MemorySegment seg, int x) {
        AVClass.version$VH.set(seg, x);
    }
    public static int version$get(MemorySegment seg, long index) {
        return (int)AVClass.version$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void version$set(MemorySegment seg, long index, int x) {
        AVClass.version$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle log_level_offset_offset$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("log_level_offset_offset"));
    public static VarHandle log_level_offset_offset$VH() {
        return AVClass.log_level_offset_offset$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int log_level_offset_offset;
     * }
     */
    public static int log_level_offset_offset$get(MemorySegment seg) {
        return (int)AVClass.log_level_offset_offset$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int log_level_offset_offset;
     * }
     */
    public static void log_level_offset_offset$set(MemorySegment seg, int x) {
        AVClass.log_level_offset_offset$VH.set(seg, x);
    }
    public static int log_level_offset_offset$get(MemorySegment seg, long index) {
        return (int)AVClass.log_level_offset_offset$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void log_level_offset_offset$set(MemorySegment seg, long index, int x) {
        AVClass.log_level_offset_offset$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle parent_log_context_offset$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("parent_log_context_offset"));
    public static VarHandle parent_log_context_offset$VH() {
        return AVClass.parent_log_context_offset$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int parent_log_context_offset;
     * }
     */
    public static int parent_log_context_offset$get(MemorySegment seg) {
        return (int)AVClass.parent_log_context_offset$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int parent_log_context_offset;
     * }
     */
    public static void parent_log_context_offset$set(MemorySegment seg, int x) {
        AVClass.parent_log_context_offset$VH.set(seg, x);
    }
    public static int parent_log_context_offset$get(MemorySegment seg, long index) {
        return (int)AVClass.parent_log_context_offset$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void parent_log_context_offset$set(MemorySegment seg, long index, int x) {
        AVClass.parent_log_context_offset$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle category$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("category"));
    public static VarHandle category$VH() {
        return AVClass.category$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * AVClassCategory category;
     * }
     */
    public static int category$get(MemorySegment seg) {
        return (int)AVClass.category$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * AVClassCategory category;
     * }
     */
    public static void category$set(MemorySegment seg, int x) {
        AVClass.category$VH.set(seg, x);
    }
    public static int category$get(MemorySegment seg, long index) {
        return (int)AVClass.category$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void category$set(MemorySegment seg, long index, int x) {
        AVClass.category$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final FunctionDescriptor get_category$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor get_category_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle get_category_UP$MH = RuntimeHelper.upcallHandle(get_category.class, "apply", AVClass.get_category_UP$FUNC);
    static final FunctionDescriptor get_category_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle get_category_DOWN$MH = RuntimeHelper.downcallHandle(
        AVClass.get_category_DOWN$FUNC
    );
    /**
     * {@snippet :
 * AVClassCategory (*get_category)(void*);
     * }
     */
    public interface get_category {

        int apply(java.lang.foreign.MemorySegment _x0);
        static MemorySegment allocate(get_category fi, SegmentScope scope) {
            return RuntimeHelper.upcallStub(AVClass.get_category_UP$MH, fi, AVClass.get_category$FUNC, scope);
        }
        static get_category ofAddress(MemorySegment addr, SegmentScope scope) {
            MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
            return (java.lang.foreign.MemorySegment __x0) -> {
                try {
                    return (int)AVClass.get_category_DOWN$MH.invokeExact(symbol, __x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle get_category$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("get_category"));
    public static VarHandle get_category$VH() {
        return AVClass.get_category$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * AVClassCategory (*get_category)(void*);
     * }
     */
    public static MemorySegment get_category$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)AVClass.get_category$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * AVClassCategory (*get_category)(void*);
     * }
     */
    public static void get_category$set(MemorySegment seg, MemorySegment x) {
        AVClass.get_category$VH.set(seg, x);
    }
    public static MemorySegment get_category$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)AVClass.get_category$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void get_category$set(MemorySegment seg, long index, MemorySegment x) {
        AVClass.get_category$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static get_category get_category(MemorySegment segment, SegmentScope scope) {
        return get_category.ofAddress(get_category$get(segment), scope);
    }
    static final FunctionDescriptor query_ranges$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final FunctionDescriptor query_ranges_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle query_ranges_UP$MH = RuntimeHelper.upcallHandle(query_ranges.class, "apply", AVClass.query_ranges_UP$FUNC);
    static final FunctionDescriptor query_ranges_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle query_ranges_DOWN$MH = RuntimeHelper.downcallHandle(
        AVClass.query_ranges_DOWN$FUNC
    );
    /**
     * {@snippet :
 * int (*query_ranges)(struct AVOptionRanges**,void*,char*,int);
     * }
     */
    public interface query_ranges {

        int apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _x1, java.lang.foreign.MemorySegment _x2, int _x3);
        static MemorySegment allocate(query_ranges fi, SegmentScope scope) {
            return RuntimeHelper.upcallStub(AVClass.query_ranges_UP$MH, fi, AVClass.query_ranges$FUNC, scope);
        }
        static query_ranges ofAddress(MemorySegment addr, SegmentScope scope) {
            MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
            return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __x1, java.lang.foreign.MemorySegment __x2, int __x3) -> {
                try {
                    return (int)AVClass.query_ranges_DOWN$MH.invokeExact(symbol, __x0, __x1, __x2, __x3);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle query_ranges$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("query_ranges"));
    public static VarHandle query_ranges$VH() {
        return AVClass.query_ranges$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int (*query_ranges)(struct AVOptionRanges**,void*,char*,int);
     * }
     */
    public static MemorySegment query_ranges$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)AVClass.query_ranges$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int (*query_ranges)(struct AVOptionRanges**,void*,char*,int);
     * }
     */
    public static void query_ranges$set(MemorySegment seg, MemorySegment x) {
        AVClass.query_ranges$VH.set(seg, x);
    }
    public static MemorySegment query_ranges$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)AVClass.query_ranges$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void query_ranges$set(MemorySegment seg, long index, MemorySegment x) {
        AVClass.query_ranges$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static query_ranges query_ranges(MemorySegment segment, SegmentScope scope) {
        return query_ranges.ofAddress(query_ranges$get(segment), scope);
    }
    static final FunctionDescriptor child_next$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor child_next_UP$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle child_next_UP$MH = RuntimeHelper.upcallHandle(child_next.class, "apply", AVClass.child_next_UP$FUNC);
    static final FunctionDescriptor child_next_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle child_next_DOWN$MH = RuntimeHelper.downcallHandle(
        AVClass.child_next_DOWN$FUNC
    );
    /**
     * {@snippet :
 * void* (*child_next)(void*,void*);
     * }
     */
    public interface child_next {

        java.lang.foreign.MemorySegment apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _x1);
        static MemorySegment allocate(child_next fi, SegmentScope scope) {
            return RuntimeHelper.upcallStub(AVClass.child_next_UP$MH, fi, AVClass.child_next$FUNC, scope);
        }
        static child_next ofAddress(MemorySegment addr, SegmentScope scope) {
            MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
            return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __x1) -> {
                try {
                    return (java.lang.foreign.MemorySegment)AVClass.child_next_DOWN$MH.invokeExact(symbol, __x0, __x1);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle child_next$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("child_next"));
    public static VarHandle child_next$VH() {
        return AVClass.child_next$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* (*child_next)(void*,void*);
     * }
     */
    public static MemorySegment child_next$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)AVClass.child_next$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* (*child_next)(void*,void*);
     * }
     */
    public static void child_next$set(MemorySegment seg, MemorySegment x) {
        AVClass.child_next$VH.set(seg, x);
    }
    public static MemorySegment child_next$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)AVClass.child_next$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void child_next$set(MemorySegment seg, long index, MemorySegment x) {
        AVClass.child_next$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static child_next child_next(MemorySegment segment, SegmentScope scope) {
        return child_next.ofAddress(child_next$get(segment), scope);
    }
    static final FunctionDescriptor child_class_iterate$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor child_class_iterate_UP$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle child_class_iterate_UP$MH = RuntimeHelper.upcallHandle(child_class_iterate.class, "apply", AVClass.child_class_iterate_UP$FUNC);
    static final FunctionDescriptor child_class_iterate_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle child_class_iterate_DOWN$MH = RuntimeHelper.downcallHandle(
        AVClass.child_class_iterate_DOWN$FUNC
    );
    /**
     * {@snippet :
 * struct AVClass* (*child_class_iterate)(void**);
     * }
     */
    public interface child_class_iterate {

        java.lang.foreign.MemorySegment apply(java.lang.foreign.MemorySegment _x0);
        static MemorySegment allocate(child_class_iterate fi, SegmentScope scope) {
            return RuntimeHelper.upcallStub(AVClass.child_class_iterate_UP$MH, fi, AVClass.child_class_iterate$FUNC, scope);
        }
        static child_class_iterate ofAddress(MemorySegment addr, SegmentScope scope) {
            MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
            return (java.lang.foreign.MemorySegment __x0) -> {
                try {
                    return (java.lang.foreign.MemorySegment)AVClass.child_class_iterate_DOWN$MH.invokeExact(symbol, __x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle child_class_iterate$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("child_class_iterate"));
    public static VarHandle child_class_iterate$VH() {
        return AVClass.child_class_iterate$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct AVClass* (*child_class_iterate)(void**);
     * }
     */
    public static MemorySegment child_class_iterate$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)AVClass.child_class_iterate$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct AVClass* (*child_class_iterate)(void**);
     * }
     */
    public static void child_class_iterate$set(MemorySegment seg, MemorySegment x) {
        AVClass.child_class_iterate$VH.set(seg, x);
    }
    public static MemorySegment child_class_iterate$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)AVClass.child_class_iterate$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void child_class_iterate$set(MemorySegment seg, long index, MemorySegment x) {
        AVClass.child_class_iterate$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static child_class_iterate child_class_iterate(MemorySegment segment, SegmentScope scope) {
        return child_class_iterate.ofAddress(child_class_iterate$get(segment), scope);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


