// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct AVIODirContext {
 *     struct URLContext* url_context;
 * };
 * }
 */
public class AVIODirContext {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("url_context")
    ).withName("AVIODirContext");
    public static MemoryLayout $LAYOUT() {
        return AVIODirContext.$struct$LAYOUT;
    }
    static final VarHandle url_context$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("url_context"));
    public static VarHandle url_context$VH() {
        return AVIODirContext.url_context$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * struct URLContext* url_context;
     * }
     */
    public static MemorySegment url_context$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)AVIODirContext.url_context$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * struct URLContext* url_context;
     * }
     */
    public static void url_context$set(MemorySegment seg, MemorySegment x) {
        AVIODirContext.url_context$VH.set(seg, x);
    }
    public static MemorySegment url_context$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)AVIODirContext.url_context$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void url_context$set(MemorySegment seg, long index, MemorySegment x) {
        AVIODirContext.url_context$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


