// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct AVPacketSideData {
 *     uint8_t* data;
 *     size_t size;
 *     enum AVPacketSideDataType type;
 * };
 * }
 */
public class AVPacketSideData {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("data"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("size"),
        Constants$root.C_LONG$LAYOUT.withName("type"),
        MemoryLayout.paddingLayout(32)
    ).withName("AVPacketSideData");
    public static MemoryLayout $LAYOUT() {
        return AVPacketSideData.$struct$LAYOUT;
    }
    static final VarHandle data$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("data"));
    public static VarHandle data$VH() {
        return AVPacketSideData.data$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint8_t* data;
     * }
     */
    public static MemorySegment data$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)AVPacketSideData.data$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint8_t* data;
     * }
     */
    public static void data$set(MemorySegment seg, MemorySegment x) {
        AVPacketSideData.data$VH.set(seg, x);
    }
    public static MemorySegment data$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)AVPacketSideData.data$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void data$set(MemorySegment seg, long index, MemorySegment x) {
        AVPacketSideData.data$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle size$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("size"));
    public static VarHandle size$VH() {
        return AVPacketSideData.size$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * size_t size;
     * }
     */
    public static long size$get(MemorySegment seg) {
        return (long)AVPacketSideData.size$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * size_t size;
     * }
     */
    public static void size$set(MemorySegment seg, long x) {
        AVPacketSideData.size$VH.set(seg, x);
    }
    public static long size$get(MemorySegment seg, long index) {
        return (long)AVPacketSideData.size$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void size$set(MemorySegment seg, long index, long x) {
        AVPacketSideData.size$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle type$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("type"));
    public static VarHandle type$VH() {
        return AVPacketSideData.type$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enum AVPacketSideDataType type;
     * }
     */
    public static int type$get(MemorySegment seg) {
        return (int)AVPacketSideData.type$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enum AVPacketSideDataType type;
     * }
     */
    public static void type$set(MemorySegment seg, int x) {
        AVPacketSideData.type$VH.set(seg, x);
    }
    public static int type$get(MemorySegment seg, long index) {
        return (int)AVPacketSideData.type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void type$set(MemorySegment seg, long index, int x) {
        AVPacketSideData.type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


