// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct AVRational {
 *     int num;
 *     int den;
 * };
 * }
 */
public class AVRational {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("num"),
        Constants$root.C_LONG$LAYOUT.withName("den")
    ).withName("AVRational");
    public static MemoryLayout $LAYOUT() {
        return AVRational.$struct$LAYOUT;
    }
    static final VarHandle num$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("num"));
    public static VarHandle num$VH() {
        return AVRational.num$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int num;
     * }
     */
    public static int num$get(MemorySegment seg) {
        return (int)AVRational.num$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int num;
     * }
     */
    public static void num$set(MemorySegment seg, int x) {
        AVRational.num$VH.set(seg, x);
    }
    public static int num$get(MemorySegment seg, long index) {
        return (int)AVRational.num$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void num$set(MemorySegment seg, long index, int x) {
        AVRational.num$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle den$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("den"));
    public static VarHandle den$VH() {
        return AVRational.den$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int den;
     * }
     */
    public static int den$get(MemorySegment seg) {
        return (int)AVRational.den$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int den;
     * }
     */
    public static void den$set(MemorySegment seg, int x) {
        AVRational.den$VH.set(seg, x);
    }
    public static int den$get(MemorySegment seg, long index) {
        return (int)AVRational.den$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void den$set(MemorySegment seg, long index, int x) {
        AVRational.den$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


