// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct AVSubtitleRect {
 *     int x;
 *     int y;
 *     int w;
 *     int h;
 *     int nb_colors;
 *     uint8_t* data[4];
 *     int linesize[4];
 *     enum AVSubtitleType type;
 *     char* text;
 *     char* ass;
 *     int flags;
 * };
 * }
 */
public class AVSubtitleRect {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("x"),
        Constants$root.C_LONG$LAYOUT.withName("y"),
        Constants$root.C_LONG$LAYOUT.withName("w"),
        Constants$root.C_LONG$LAYOUT.withName("h"),
        Constants$root.C_LONG$LAYOUT.withName("nb_colors"),
        MemoryLayout.paddingLayout(32),
        MemoryLayout.sequenceLayout(4, Constants$root.C_POINTER$LAYOUT).withName("data"),
        MemoryLayout.sequenceLayout(4, Constants$root.C_LONG$LAYOUT).withName("linesize"),
        Constants$root.C_LONG$LAYOUT.withName("type"),
        MemoryLayout.paddingLayout(32),
        Constants$root.C_POINTER$LAYOUT.withName("text"),
        Constants$root.C_POINTER$LAYOUT.withName("ass"),
        Constants$root.C_LONG$LAYOUT.withName("flags"),
        MemoryLayout.paddingLayout(32)
    ).withName("AVSubtitleRect");
    public static MemoryLayout $LAYOUT() {
        return AVSubtitleRect.$struct$LAYOUT;
    }
    static final VarHandle x$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("x"));
    public static VarHandle x$VH() {
        return AVSubtitleRect.x$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int x;
     * }
     */
    public static int x$get(MemorySegment seg) {
        return (int)AVSubtitleRect.x$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int x;
     * }
     */
    public static void x$set(MemorySegment seg, int x) {
        AVSubtitleRect.x$VH.set(seg, x);
    }
    public static int x$get(MemorySegment seg, long index) {
        return (int)AVSubtitleRect.x$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void x$set(MemorySegment seg, long index, int x) {
        AVSubtitleRect.x$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle y$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("y"));
    public static VarHandle y$VH() {
        return AVSubtitleRect.y$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int y;
     * }
     */
    public static int y$get(MemorySegment seg) {
        return (int)AVSubtitleRect.y$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int y;
     * }
     */
    public static void y$set(MemorySegment seg, int x) {
        AVSubtitleRect.y$VH.set(seg, x);
    }
    public static int y$get(MemorySegment seg, long index) {
        return (int)AVSubtitleRect.y$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void y$set(MemorySegment seg, long index, int x) {
        AVSubtitleRect.y$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle w$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("w"));
    public static VarHandle w$VH() {
        return AVSubtitleRect.w$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int w;
     * }
     */
    public static int w$get(MemorySegment seg) {
        return (int)AVSubtitleRect.w$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int w;
     * }
     */
    public static void w$set(MemorySegment seg, int x) {
        AVSubtitleRect.w$VH.set(seg, x);
    }
    public static int w$get(MemorySegment seg, long index) {
        return (int)AVSubtitleRect.w$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void w$set(MemorySegment seg, long index, int x) {
        AVSubtitleRect.w$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle h$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("h"));
    public static VarHandle h$VH() {
        return AVSubtitleRect.h$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int h;
     * }
     */
    public static int h$get(MemorySegment seg) {
        return (int)AVSubtitleRect.h$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int h;
     * }
     */
    public static void h$set(MemorySegment seg, int x) {
        AVSubtitleRect.h$VH.set(seg, x);
    }
    public static int h$get(MemorySegment seg, long index) {
        return (int)AVSubtitleRect.h$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void h$set(MemorySegment seg, long index, int x) {
        AVSubtitleRect.h$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle nb_colors$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("nb_colors"));
    public static VarHandle nb_colors$VH() {
        return AVSubtitleRect.nb_colors$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int nb_colors;
     * }
     */
    public static int nb_colors$get(MemorySegment seg) {
        return (int)AVSubtitleRect.nb_colors$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int nb_colors;
     * }
     */
    public static void nb_colors$set(MemorySegment seg, int x) {
        AVSubtitleRect.nb_colors$VH.set(seg, x);
    }
    public static int nb_colors$get(MemorySegment seg, long index) {
        return (int)AVSubtitleRect.nb_colors$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void nb_colors$set(MemorySegment seg, long index, int x) {
        AVSubtitleRect.nb_colors$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment data$slice(MemorySegment seg) {
        return seg.asSlice(24, 32);
    }
    public static MemorySegment linesize$slice(MemorySegment seg) {
        return seg.asSlice(56, 16);
    }
    static final VarHandle type$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("type"));
    public static VarHandle type$VH() {
        return AVSubtitleRect.type$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enum AVSubtitleType type;
     * }
     */
    public static int type$get(MemorySegment seg) {
        return (int)AVSubtitleRect.type$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enum AVSubtitleType type;
     * }
     */
    public static void type$set(MemorySegment seg, int x) {
        AVSubtitleRect.type$VH.set(seg, x);
    }
    public static int type$get(MemorySegment seg, long index) {
        return (int)AVSubtitleRect.type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void type$set(MemorySegment seg, long index, int x) {
        AVSubtitleRect.type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle text$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("text"));
    public static VarHandle text$VH() {
        return AVSubtitleRect.text$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* text;
     * }
     */
    public static MemorySegment text$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)AVSubtitleRect.text$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* text;
     * }
     */
    public static void text$set(MemorySegment seg, MemorySegment x) {
        AVSubtitleRect.text$VH.set(seg, x);
    }
    public static MemorySegment text$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)AVSubtitleRect.text$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void text$set(MemorySegment seg, long index, MemorySegment x) {
        AVSubtitleRect.text$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle ass$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("ass"));
    public static VarHandle ass$VH() {
        return AVSubtitleRect.ass$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* ass;
     * }
     */
    public static MemorySegment ass$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)AVSubtitleRect.ass$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* ass;
     * }
     */
    public static void ass$set(MemorySegment seg, MemorySegment x) {
        AVSubtitleRect.ass$VH.set(seg, x);
    }
    public static MemorySegment ass$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)AVSubtitleRect.ass$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void ass$set(MemorySegment seg, long index, MemorySegment x) {
        AVSubtitleRect.ass$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle flags$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("flags"));
    public static VarHandle flags$VH() {
        return AVSubtitleRect.flags$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int flags;
     * }
     */
    public static int flags$get(MemorySegment seg) {
        return (int)AVSubtitleRect.flags$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int flags;
     * }
     */
    public static void flags$set(MemorySegment seg, int x) {
        AVSubtitleRect.flags$VH.set(seg, x);
    }
    public static int flags$get(MemorySegment seg, long index) {
        return (int)AVSubtitleRect.flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void flags$set(MemorySegment seg, long index, int x) {
        AVSubtitleRect.flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


