// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$133 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$133() {}
    static final FunctionDescriptor av_buffer_make_writable$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_buffer_make_writable$MH = RuntimeHelper.downcallHandle(
        "av_buffer_make_writable",
        constants$133.av_buffer_make_writable$FUNC
    );
    static final FunctionDescriptor av_buffer_realloc$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle av_buffer_realloc$MH = RuntimeHelper.downcallHandle(
        "av_buffer_realloc",
        constants$133.av_buffer_realloc$FUNC
    );
    static final FunctionDescriptor av_buffer_replace$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_buffer_replace$MH = RuntimeHelper.downcallHandle(
        "av_buffer_replace",
        constants$133.av_buffer_replace$FUNC
    );
    static final FunctionDescriptor av_buffer_pool_init$alloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final FunctionDescriptor av_buffer_pool_init$alloc_UP$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle av_buffer_pool_init$alloc_UP$MH = RuntimeHelper.upcallHandle(av_buffer_pool_init$alloc.class, "apply", constants$133.av_buffer_pool_init$alloc_UP$FUNC);
    static final FunctionDescriptor av_buffer_pool_init$alloc_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle av_buffer_pool_init$alloc_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$133.av_buffer_pool_init$alloc_DOWN$FUNC
    );
    static final FunctionDescriptor av_buffer_pool_init$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_buffer_pool_init$MH = RuntimeHelper.downcallHandle(
        "av_buffer_pool_init",
        constants$133.av_buffer_pool_init$FUNC
    );
}


