// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final FunctionDescriptor av_get_picture_type_char$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_get_picture_type_char$MH = RuntimeHelper.downcallHandle(
        "av_get_picture_type_char",
        constants$4.av_get_picture_type_char$FUNC
    );
    static final FunctionDescriptor _invalid_parameter_noinfo$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle _invalid_parameter_noinfo$MH = RuntimeHelper.downcallHandle(
        "_invalid_parameter_noinfo",
        constants$4._invalid_parameter_noinfo$FUNC
    );
    static final FunctionDescriptor _invalid_parameter_noinfo_noreturn$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle _invalid_parameter_noinfo_noreturn$MH = RuntimeHelper.downcallHandle(
        "_invalid_parameter_noinfo_noreturn",
        constants$4._invalid_parameter_noinfo_noreturn$FUNC
    );
    static final FunctionDescriptor _invoke_watson$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _invoke_watson$MH = RuntimeHelper.downcallHandle(
        "_invoke_watson",
        constants$4._invoke_watson$FUNC
    );
    static final FunctionDescriptor _errno$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle _errno$MH = RuntimeHelper.downcallHandle(
        "_errno",
        constants$4._errno$FUNC
    );
    static final FunctionDescriptor _set_errno$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _set_errno$MH = RuntimeHelper.downcallHandle(
        "_set_errno",
        constants$4._set_errno$FUNC
    );
}


