// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$10 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$10() {}
    static final FunctionDescriptor _fdscale$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _fdscale$MH = RuntimeHelper.downcallHandle(
        "_fdscale",
        constants$10._fdscale$FUNC
    );
    static final FunctionDescriptor _dunscale$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _dunscale$MH = RuntimeHelper.downcallHandle(
        "_dunscale",
        constants$10._dunscale$FUNC
    );
    static final FunctionDescriptor _ldunscale$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _ldunscale$MH = RuntimeHelper.downcallHandle(
        "_ldunscale",
        constants$10._ldunscale$FUNC
    );
    static final FunctionDescriptor _fdunscale$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _fdunscale$MH = RuntimeHelper.downcallHandle(
        "_fdunscale",
        constants$10._fdunscale$FUNC
    );
    static final FunctionDescriptor _dexp$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _dexp$MH = RuntimeHelper.downcallHandle(
        "_dexp",
        constants$10._dexp$FUNC
    );
    static final FunctionDescriptor _fdexp$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _fdexp$MH = RuntimeHelper.downcallHandle(
        "_fdexp",
        constants$10._fdexp$FUNC
    );
}


