// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$189 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$189() {}
    static final FunctionDescriptor avformat_open_input$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avformat_open_input$MH = RuntimeHelper.downcallHandle(
        "avformat_open_input",
        constants$189.avformat_open_input$FUNC
    );
    static final FunctionDescriptor avformat_find_stream_info$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avformat_find_stream_info$MH = RuntimeHelper.downcallHandle(
        "avformat_find_stream_info",
        constants$189.avformat_find_stream_info$FUNC
    );
    static final FunctionDescriptor av_find_program_from_stream$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_find_program_from_stream$MH = RuntimeHelper.downcallHandle(
        "av_find_program_from_stream",
        constants$189.av_find_program_from_stream$FUNC
    );
    static final FunctionDescriptor av_program_add_stream_index$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_program_add_stream_index$MH = RuntimeHelper.downcallHandle(
        "av_program_add_stream_index",
        constants$189.av_program_add_stream_index$FUNC
    );
    static final FunctionDescriptor av_find_best_stream$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_find_best_stream$MH = RuntimeHelper.downcallHandle(
        "av_find_best_stream",
        constants$189.av_find_best_stream$FUNC
    );
    static final FunctionDescriptor av_read_frame$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_read_frame$MH = RuntimeHelper.downcallHandle(
        "av_read_frame",
        constants$189.av_read_frame$FUNC
    );
}


