// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$106 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$106() {}
    static final FunctionDescriptor _wcslwr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcslwr$MH = RuntimeHelper.downcallHandle(
        "_wcslwr",
        constants$106._wcslwr$FUNC
    );
    static final FunctionDescriptor _wcslwr_s_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcslwr_s_l$MH = RuntimeHelper.downcallHandle(
        "_wcslwr_s_l",
        constants$106._wcslwr_s_l$FUNC
    );
    static final FunctionDescriptor _wcslwr_l$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcslwr_l$MH = RuntimeHelper.downcallHandle(
        "_wcslwr_l",
        constants$106._wcslwr_l$FUNC
    );
    static final FunctionDescriptor _wcsupr_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _wcsupr_s$MH = RuntimeHelper.downcallHandle(
        "_wcsupr_s",
        constants$106._wcsupr_s$FUNC
    );
    static final FunctionDescriptor _wcsupr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcsupr$MH = RuntimeHelper.downcallHandle(
        "_wcsupr",
        constants$106._wcsupr$FUNC
    );
    static final FunctionDescriptor _wcsupr_s_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcsupr_s_l$MH = RuntimeHelper.downcallHandle(
        "_wcsupr_s_l",
        constants$106._wcsupr_s_l$FUNC
    );
}


