// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$156 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$156() {}
    static final FunctionDescriptor avcodec_configuration$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle avcodec_configuration$MH = RuntimeHelper.downcallHandle(
        "avcodec_configuration",
        constants$156.avcodec_configuration$FUNC
    );
    static final FunctionDescriptor avcodec_license$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle avcodec_license$MH = RuntimeHelper.downcallHandle(
        "avcodec_license",
        constants$156.avcodec_license$FUNC
    );
    static final FunctionDescriptor avcodec_alloc_context3$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avcodec_alloc_context3$MH = RuntimeHelper.downcallHandle(
        "avcodec_alloc_context3",
        constants$156.avcodec_alloc_context3$FUNC
    );
    static final FunctionDescriptor avcodec_free_context$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avcodec_free_context$MH = RuntimeHelper.downcallHandle(
        "avcodec_free_context",
        constants$156.avcodec_free_context$FUNC
    );
    static final FunctionDescriptor avcodec_get_class$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle avcodec_get_class$MH = RuntimeHelper.downcallHandle(
        "avcodec_get_class",
        constants$156.avcodec_get_class$FUNC
    );
    static final FunctionDescriptor avcodec_get_subtitle_rect_class$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle avcodec_get_subtitle_rect_class$MH = RuntimeHelper.downcallHandle(
        "avcodec_get_subtitle_rect_class",
        constants$156.avcodec_get_subtitle_rect_class$FUNC
    );
}


