// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$55 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$55() {}
    static final FunctionDescriptor _getc_nolock$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _getc_nolock$MH = RuntimeHelper.downcallHandle(
        "_getc_nolock",
        constants$55._getc_nolock$FUNC
    );
    static final FunctionDescriptor _putc_nolock$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _putc_nolock$MH = RuntimeHelper.downcallHandle(
        "_putc_nolock",
        constants$55._putc_nolock$FUNC
    );
    static final FunctionDescriptor _ungetc_nolock$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _ungetc_nolock$MH = RuntimeHelper.downcallHandle(
        "_ungetc_nolock",
        constants$55._ungetc_nolock$FUNC
    );
    static final FunctionDescriptor __p__commode$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle __p__commode$MH = RuntimeHelper.downcallHandle(
        "__p__commode",
        constants$55.__p__commode$FUNC
    );
    static final FunctionDescriptor __stdio_common_vfprintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __stdio_common_vfprintf$MH = RuntimeHelper.downcallHandle(
        "__stdio_common_vfprintf",
        constants$55.__stdio_common_vfprintf$FUNC
    );
    static final FunctionDescriptor __stdio_common_vfprintf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __stdio_common_vfprintf_s$MH = RuntimeHelper.downcallHandle(
        "__stdio_common_vfprintf_s",
        constants$55.__stdio_common_vfprintf_s$FUNC
    );
}


