// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$192 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$192() {}
    static final FunctionDescriptor av_write_uncoded_frame_query$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_write_uncoded_frame_query$MH = RuntimeHelper.downcallHandle(
        "av_write_uncoded_frame_query",
        constants$192.av_write_uncoded_frame_query$FUNC
    );
    static final FunctionDescriptor av_write_trailer$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_write_trailer$MH = RuntimeHelper.downcallHandle(
        "av_write_trailer",
        constants$192.av_write_trailer$FUNC
    );
    static final FunctionDescriptor av_guess_format$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_guess_format$MH = RuntimeHelper.downcallHandle(
        "av_guess_format",
        constants$192.av_guess_format$FUNC
    );
    static final FunctionDescriptor av_guess_codec$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_guess_codec$MH = RuntimeHelper.downcallHandle(
        "av_guess_codec",
        constants$192.av_guess_codec$FUNC
    );
    static final FunctionDescriptor av_get_output_timestamp$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_get_output_timestamp$MH = RuntimeHelper.downcallHandle(
        "av_get_output_timestamp",
        constants$192.av_get_output_timestamp$FUNC
    );
    static final FunctionDescriptor av_hex_dump$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_hex_dump$MH = RuntimeHelper.downcallHandle(
        "av_hex_dump",
        constants$192.av_hex_dump$FUNC
    );
}


