// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$22 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$22() {}
    static final FunctionDescriptor modf$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle modf$MH = RuntimeHelper.downcallHandle(
        "modf",
        constants$22.modf$FUNC
    );
    static final FunctionDescriptor nan$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nan$MH = RuntimeHelper.downcallHandle(
        "nan",
        constants$22.nan$FUNC
    );
    static final FunctionDescriptor nearbyint$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle nearbyint$MH = RuntimeHelper.downcallHandle(
        "nearbyint",
        constants$22.nearbyint$FUNC
    );
    static final FunctionDescriptor nextafter$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle nextafter$MH = RuntimeHelper.downcallHandle(
        "nextafter",
        constants$22.nextafter$FUNC
    );
    static final FunctionDescriptor remainder$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle remainder$MH = RuntimeHelper.downcallHandle(
        "remainder",
        constants$22.remainder$FUNC
    );
    static final FunctionDescriptor remquo$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle remquo$MH = RuntimeHelper.downcallHandle(
        "remquo",
        constants$22.remquo$FUNC
    );
}


