// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$72 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$72() {}
    static final FunctionDescriptor _wdupenv_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wdupenv_s$MH = RuntimeHelper.downcallHandle(
        "_wdupenv_s",
        constants$72._wdupenv_s$FUNC
    );
    static final FunctionDescriptor _wgetenv$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wgetenv$MH = RuntimeHelper.downcallHandle(
        "_wgetenv",
        constants$72._wgetenv$FUNC
    );
    static final FunctionDescriptor _wgetenv_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wgetenv_s$MH = RuntimeHelper.downcallHandle(
        "_wgetenv_s",
        constants$72._wgetenv_s$FUNC
    );
    static final FunctionDescriptor _wputenv$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wputenv$MH = RuntimeHelper.downcallHandle(
        "_wputenv",
        constants$72._wputenv$FUNC
    );
    static final FunctionDescriptor _wputenv_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wputenv_s$MH = RuntimeHelper.downcallHandle(
        "_wputenv_s",
        constants$72._wputenv_s$FUNC
    );
    static final FunctionDescriptor _wsearchenv_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _wsearchenv_s$MH = RuntimeHelper.downcallHandle(
        "_wsearchenv_s",
        constants$72._wsearchenv_s$FUNC
    );
}


