// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$56 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$56() {}
    static final FunctionDescriptor __stdio_common_vfprintf_p$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __stdio_common_vfprintf_p$MH = RuntimeHelper.downcallHandle(
        "__stdio_common_vfprintf_p",
        constants$56.__stdio_common_vfprintf_p$FUNC
    );
    static final FunctionDescriptor _set_printf_count_output$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _set_printf_count_output$MH = RuntimeHelper.downcallHandle(
        "_set_printf_count_output",
        constants$56._set_printf_count_output$FUNC
    );
    static final FunctionDescriptor _get_printf_count_output$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle _get_printf_count_output$MH = RuntimeHelper.downcallHandle(
        "_get_printf_count_output",
        constants$56._get_printf_count_output$FUNC
    );
    static final FunctionDescriptor __stdio_common_vfscanf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __stdio_common_vfscanf$MH = RuntimeHelper.downcallHandle(
        "__stdio_common_vfscanf",
        constants$56.__stdio_common_vfscanf$FUNC
    );
    static final FunctionDescriptor __stdio_common_vsprintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __stdio_common_vsprintf$MH = RuntimeHelper.downcallHandle(
        "__stdio_common_vsprintf",
        constants$56.__stdio_common_vsprintf$FUNC
    );
    static final FunctionDescriptor __stdio_common_vsprintf_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __stdio_common_vsprintf_s$MH = RuntimeHelper.downcallHandle(
        "__stdio_common_vsprintf_s",
        constants$56.__stdio_common_vsprintf_s$FUNC
    );
}


