// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$179 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$179() {}
    static final FunctionDescriptor avio_rl16$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avio_rl16$MH = RuntimeHelper.downcallHandle(
        "avio_rl16",
        constants$179.avio_rl16$FUNC
    );
    static final FunctionDescriptor avio_rl24$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avio_rl24$MH = RuntimeHelper.downcallHandle(
        "avio_rl24",
        constants$179.avio_rl24$FUNC
    );
    static final FunctionDescriptor avio_rl32$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avio_rl32$MH = RuntimeHelper.downcallHandle(
        "avio_rl32",
        constants$179.avio_rl32$FUNC
    );
    static final FunctionDescriptor avio_rl64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avio_rl64$MH = RuntimeHelper.downcallHandle(
        "avio_rl64",
        constants$179.avio_rl64$FUNC
    );
    static final FunctionDescriptor avio_rb16$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avio_rb16$MH = RuntimeHelper.downcallHandle(
        "avio_rb16",
        constants$179.avio_rb16$FUNC
    );
    static final FunctionDescriptor avio_rb24$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avio_rb24$MH = RuntimeHelper.downcallHandle(
        "avio_rb24",
        constants$179.avio_rb24$FUNC
    );
}


