// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$131 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$131() {}
    static final FunctionDescriptor av_fourcc_make_string$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_fourcc_make_string$MH = RuntimeHelper.downcallHandle(
        "av_fourcc_make_string",
        constants$131.av_fourcc_make_string$FUNC
    );
    static final FunctionDescriptor av_buffer_alloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle av_buffer_alloc$MH = RuntimeHelper.downcallHandle(
        "av_buffer_alloc",
        constants$131.av_buffer_alloc$FUNC
    );
    static final FunctionDescriptor av_buffer_allocz$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle av_buffer_allocz$MH = RuntimeHelper.downcallHandle(
        "av_buffer_allocz",
        constants$131.av_buffer_allocz$FUNC
    );
    static final FunctionDescriptor av_buffer_create$free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor av_buffer_create$free_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_buffer_create$free_UP$MH = RuntimeHelper.upcallHandle(av_buffer_create$free.class, "apply", constants$131.av_buffer_create$free_UP$FUNC);
    static final FunctionDescriptor av_buffer_create$free_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_buffer_create$free_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$131.av_buffer_create$free_DOWN$FUNC
    );
    static final FunctionDescriptor av_buffer_create$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_buffer_create$MH = RuntimeHelper.downcallHandle(
        "av_buffer_create",
        constants$131.av_buffer_create$FUNC
    );
}


