// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$63 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$63() {}
    static final FunctionDescriptor _CoreCrtSecureSearchSortCompareFunction_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _CoreCrtSecureSearchSortCompareFunction_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$63._CoreCrtSecureSearchSortCompareFunction_DOWN$FUNC
    );
    static final FunctionDescriptor _CoreCrtNonSecureSearchSortCompareFunction$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor _CoreCrtNonSecureSearchSortCompareFunction_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _CoreCrtNonSecureSearchSortCompareFunction_UP$MH = RuntimeHelper.upcallHandle(_CoreCrtNonSecureSearchSortCompareFunction.class, "apply", constants$63._CoreCrtNonSecureSearchSortCompareFunction_UP$FUNC);
    static final FunctionDescriptor _CoreCrtNonSecureSearchSortCompareFunction_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _CoreCrtNonSecureSearchSortCompareFunction_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$63._CoreCrtNonSecureSearchSortCompareFunction_DOWN$FUNC
    );
    static final FunctionDescriptor bsearch_s$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle bsearch_s$MH = RuntimeHelper.downcallHandle(
        "bsearch_s",
        constants$63.bsearch_s$FUNC
    );
    static final FunctionDescriptor qsort_s$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle qsort_s$MH = RuntimeHelper.downcallHandle(
        "qsort_s",
        constants$63.qsort_s$FUNC
    );
    static final FunctionDescriptor bsearch$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle bsearch$MH = RuntimeHelper.downcallHandle(
        "bsearch",
        constants$63.bsearch$FUNC
    );
}


