// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$83 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$83() {}
    static final FunctionDescriptor _atoi64_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _atoi64_l$MH = RuntimeHelper.downcallHandle(
        "_atoi64_l",
        constants$83._atoi64_l$FUNC
    );
    static final FunctionDescriptor _atoflt$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _atoflt$MH = RuntimeHelper.downcallHandle(
        "_atoflt",
        constants$83._atoflt$FUNC
    );
    static final FunctionDescriptor _atodbl$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _atodbl$MH = RuntimeHelper.downcallHandle(
        "_atodbl",
        constants$83._atodbl$FUNC
    );
    static final FunctionDescriptor _atoldbl$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _atoldbl$MH = RuntimeHelper.downcallHandle(
        "_atoldbl",
        constants$83._atoldbl$FUNC
    );
    static final FunctionDescriptor _atoflt_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _atoflt_l$MH = RuntimeHelper.downcallHandle(
        "_atoflt_l",
        constants$83._atoflt_l$FUNC
    );
    static final FunctionDescriptor _atodbl_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _atodbl_l$MH = RuntimeHelper.downcallHandle(
        "_atodbl_l",
        constants$83._atodbl_l$FUNC
    );
}


