// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$195 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$195() {}
    static final FunctionDescriptor av_url_split$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_url_split$MH = RuntimeHelper.downcallHandle(
        "av_url_split",
        constants$195.av_url_split$FUNC
    );
    static final FunctionDescriptor av_dump_format$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_dump_format$MH = RuntimeHelper.downcallHandle(
        "av_dump_format",
        constants$195.av_dump_format$FUNC
    );
    static final FunctionDescriptor av_get_frame_filename2$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_get_frame_filename2$MH = RuntimeHelper.downcallHandle(
        "av_get_frame_filename2",
        constants$195.av_get_frame_filename2$FUNC
    );
    static final FunctionDescriptor av_get_frame_filename$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_get_frame_filename$MH = RuntimeHelper.downcallHandle(
        "av_get_frame_filename",
        constants$195.av_get_frame_filename$FUNC
    );
    static final FunctionDescriptor av_filename_number_test$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_filename_number_test$MH = RuntimeHelper.downcallHandle(
        "av_filename_number_test",
        constants$195.av_filename_number_test$FUNC
    );
    static final FunctionDescriptor av_sdp_create$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_sdp_create$MH = RuntimeHelper.downcallHandle(
        "av_sdp_create",
        constants$195.av_sdp_create$FUNC
    );
}


