// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$237 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$237() {}
    static final MemorySegment LIBAVUTIL_IDENT$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("Lavu58.2.100");
    static final MemorySegment LIBAVCODEC_IDENT$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("Lavc60.3.100");
    static final MemorySegment LIBAVFORMAT_IDENT$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("Lavf60.3.100");
    static final MemorySegment LIBSWSCALE_IDENT$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("SwS7.1.100");
}


