// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2() {}
    static final FunctionDescriptor av_sample_fmt_is_planar$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_sample_fmt_is_planar$MH = RuntimeHelper.downcallHandle(
        "av_sample_fmt_is_planar",
        constants$2.av_sample_fmt_is_planar$FUNC
    );
    static final FunctionDescriptor av_samples_get_buffer_size$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_samples_get_buffer_size$MH = RuntimeHelper.downcallHandle(
        "av_samples_get_buffer_size",
        constants$2.av_samples_get_buffer_size$FUNC
    );
    static final FunctionDescriptor av_samples_fill_arrays$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_samples_fill_arrays$MH = RuntimeHelper.downcallHandle(
        "av_samples_fill_arrays",
        constants$2.av_samples_fill_arrays$FUNC
    );
    static final FunctionDescriptor av_samples_alloc$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_samples_alloc$MH = RuntimeHelper.downcallHandle(
        "av_samples_alloc",
        constants$2.av_samples_alloc$FUNC
    );
    static final FunctionDescriptor av_samples_alloc_array_and_samples$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_samples_alloc_array_and_samples$MH = RuntimeHelper.downcallHandle(
        "av_samples_alloc_array_and_samples",
        constants$2.av_samples_alloc_array_and_samples$FUNC
    );
    static final FunctionDescriptor av_samples_copy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_samples_copy$MH = RuntimeHelper.downcallHandle(
        "av_samples_copy",
        constants$2.av_samples_copy$FUNC
    );
}


