// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$128 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$128() {}
    static final FunctionDescriptor av_log$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_log$MH = RuntimeHelper.downcallHandleVariadic(
        "av_log",
        constants$128.av_log$FUNC
    );
    static final FunctionDescriptor av_log_once$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_log_once$MH = RuntimeHelper.downcallHandleVariadic(
        "av_log_once",
        constants$128.av_log_once$FUNC
    );
    static final FunctionDescriptor av_vlog$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_vlog$MH = RuntimeHelper.downcallHandle(
        "av_vlog",
        constants$128.av_vlog$FUNC
    );
    static final FunctionDescriptor av_log_get_level$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle av_log_get_level$MH = RuntimeHelper.downcallHandle(
        "av_log_get_level",
        constants$128.av_log_get_level$FUNC
    );
    static final FunctionDescriptor av_log_set_level$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_log_set_level$MH = RuntimeHelper.downcallHandle(
        "av_log_set_level",
        constants$128.av_log_set_level$FUNC
    );
    static final FunctionDescriptor av_log_set_callback$callback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor av_log_set_callback$callback_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_log_set_callback$callback_UP$MH = RuntimeHelper.upcallHandle(av_log_set_callback$callback.class, "apply", constants$128.av_log_set_callback$callback_UP$FUNC);
}


