// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$91 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$91() {}
    static final FunctionDescriptor _mbtowc_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mbtowc_l$MH = RuntimeHelper.downcallHandle(
        "_mbtowc_l",
        constants$91._mbtowc_l$FUNC
    );
    static final FunctionDescriptor mbstowcs_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle mbstowcs_s$MH = RuntimeHelper.downcallHandle(
        "mbstowcs_s",
        constants$91.mbstowcs_s$FUNC
    );
    static final FunctionDescriptor mbstowcs$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle mbstowcs$MH = RuntimeHelper.downcallHandle(
        "mbstowcs",
        constants$91.mbstowcs$FUNC
    );
    static final FunctionDescriptor _mbstowcs_s_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mbstowcs_s_l$MH = RuntimeHelper.downcallHandle(
        "_mbstowcs_s_l",
        constants$91._mbstowcs_s_l$FUNC
    );
    static final FunctionDescriptor _mbstowcs_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mbstowcs_l$MH = RuntimeHelper.downcallHandle(
        "_mbstowcs_l",
        constants$91._mbstowcs_l$FUNC
    );
    static final FunctionDescriptor wctomb$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle wctomb$MH = RuntimeHelper.downcallHandle(
        "wctomb",
        constants$91.wctomb$FUNC
    );
}


