// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$197 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$197() {}
    static final FunctionDescriptor av_guess_sample_aspect_ratio$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("num"),
        Constants$root.C_LONG$LAYOUT.withName("den")
    ).withName("AVRational"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_guess_sample_aspect_ratio$MH = RuntimeHelper.downcallHandle(
        "av_guess_sample_aspect_ratio",
        constants$197.av_guess_sample_aspect_ratio$FUNC
    );
    static final FunctionDescriptor av_guess_frame_rate$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("num"),
        Constants$root.C_LONG$LAYOUT.withName("den")
    ).withName("AVRational"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_guess_frame_rate$MH = RuntimeHelper.downcallHandle(
        "av_guess_frame_rate",
        constants$197.av_guess_frame_rate$FUNC
    );
    static final FunctionDescriptor avformat_match_stream_specifier$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avformat_match_stream_specifier$MH = RuntimeHelper.downcallHandle(
        "avformat_match_stream_specifier",
        constants$197.avformat_match_stream_specifier$FUNC
    );
    static final FunctionDescriptor avformat_queue_attached_pictures$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avformat_queue_attached_pictures$MH = RuntimeHelper.downcallHandle(
        "avformat_queue_attached_pictures",
        constants$197.avformat_queue_attached_pictures$FUNC
    );
    static final FunctionDescriptor avformat_transfer_internal_stream_timing_info$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle avformat_transfer_internal_stream_timing_info$MH = RuntimeHelper.downcallHandle(
        "avformat_transfer_internal_stream_timing_info",
        constants$197.avformat_transfer_internal_stream_timing_info$FUNC
    );
    static final FunctionDescriptor av_stream_get_codec_timebase$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("num"),
        Constants$root.C_LONG$LAYOUT.withName("den")
    ).withName("AVRational"),
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_stream_get_codec_timebase$MH = RuntimeHelper.downcallHandle(
        "av_stream_get_codec_timebase",
        constants$197.av_stream_get_codec_timebase$FUNC
    );
}


