// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$161 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$161() {}
    static final FunctionDescriptor avcodec_default_get_format$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avcodec_default_get_format$MH = RuntimeHelper.downcallHandle(
        "avcodec_default_get_format",
        constants$161.avcodec_default_get_format$FUNC
    );
    static final FunctionDescriptor avcodec_string$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle avcodec_string$MH = RuntimeHelper.downcallHandle(
        "avcodec_string",
        constants$161.avcodec_string$FUNC
    );
    static final FunctionDescriptor avcodec_default_execute$func$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final FunctionDescriptor avcodec_default_execute$func_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avcodec_default_execute$func_UP$MH = RuntimeHelper.upcallHandle(avcodec_default_execute$func.class, "apply", constants$161.avcodec_default_execute$func_UP$FUNC);
    static final FunctionDescriptor avcodec_default_execute$func_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avcodec_default_execute$func_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$161.avcodec_default_execute$func_DOWN$FUNC
    );
    static final FunctionDescriptor avcodec_default_execute$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle avcodec_default_execute$MH = RuntimeHelper.downcallHandle(
        "avcodec_default_execute",
        constants$161.avcodec_default_execute$FUNC
    );
    static final FunctionDescriptor avcodec_default_execute2$func$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final FunctionDescriptor avcodec_default_execute2$func_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle avcodec_default_execute2$func_UP$MH = RuntimeHelper.upcallHandle(avcodec_default_execute2$func.class, "apply", constants$161.avcodec_default_execute2$func_UP$FUNC);
}


