// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$188 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$188() {}
    static final FunctionDescriptor av_find_input_format$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_find_input_format$MH = RuntimeHelper.downcallHandle(
        "av_find_input_format",
        constants$188.av_find_input_format$FUNC
    );
    static final FunctionDescriptor av_probe_input_format$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_probe_input_format$MH = RuntimeHelper.downcallHandle(
        "av_probe_input_format",
        constants$188.av_probe_input_format$FUNC
    );
    static final FunctionDescriptor av_probe_input_format2$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_probe_input_format2$MH = RuntimeHelper.downcallHandle(
        "av_probe_input_format2",
        constants$188.av_probe_input_format2$FUNC
    );
    static final FunctionDescriptor av_probe_input_format3$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_probe_input_format3$MH = RuntimeHelper.downcallHandle(
        "av_probe_input_format3",
        constants$188.av_probe_input_format3$FUNC
    );
    static final FunctionDescriptor av_probe_input_buffer2$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_probe_input_buffer2$MH = RuntimeHelper.downcallHandle(
        "av_probe_input_buffer2",
        constants$188.av_probe_input_buffer2$FUNC
    );
    static final FunctionDescriptor av_probe_input_buffer$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_probe_input_buffer$MH = RuntimeHelper.downcallHandle(
        "av_probe_input_buffer",
        constants$188.av_probe_input_buffer$FUNC
    );
}


