// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$15 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$15() {}
    static final FunctionDescriptor log$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle log$MH = RuntimeHelper.downcallHandle(
        "log",
        constants$15.log$FUNC
    );
    static final FunctionDescriptor log10$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle log10$MH = RuntimeHelper.downcallHandle(
        "log10",
        constants$15.log10$FUNC
    );
    static final FunctionDescriptor pow$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle pow$MH = RuntimeHelper.downcallHandle(
        "pow",
        constants$15.pow$FUNC
    );
    static final FunctionDescriptor sin$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle sin$MH = RuntimeHelper.downcallHandle(
        "sin",
        constants$15.sin$FUNC
    );
    static final FunctionDescriptor sinh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle sinh$MH = RuntimeHelper.downcallHandle(
        "sinh",
        constants$15.sinh$FUNC
    );
    static final FunctionDescriptor sqrt$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle sqrt$MH = RuntimeHelper.downcallHandle(
        "sqrt",
        constants$15.sqrt$FUNC
    );
}


