// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$43 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$43() {}
    static final FunctionDescriptor __stdio_common_vswscanf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __stdio_common_vswscanf$MH = RuntimeHelper.downcallHandle(
        "__stdio_common_vswscanf",
        constants$43.__stdio_common_vswscanf$FUNC
    );
    static final FunctionDescriptor _get_stream_buffer_pointers$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _get_stream_buffer_pointers$MH = RuntimeHelper.downcallHandle(
        "_get_stream_buffer_pointers",
        constants$43._get_stream_buffer_pointers$FUNC
    );
    static final FunctionDescriptor clearerr_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle clearerr_s$MH = RuntimeHelper.downcallHandle(
        "clearerr_s",
        constants$43.clearerr_s$FUNC
    );
    static final FunctionDescriptor fopen_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fopen_s$MH = RuntimeHelper.downcallHandle(
        "fopen_s",
        constants$43.fopen_s$FUNC
    );
    static final FunctionDescriptor fread_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fread_s$MH = RuntimeHelper.downcallHandle(
        "fread_s",
        constants$43.fread_s$FUNC
    );
    static final FunctionDescriptor freopen_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle freopen_s$MH = RuntimeHelper.downcallHandle(
        "freopen_s",
        constants$43.freopen_s$FUNC
    );
}


