// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$29 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$29() {}
    static final FunctionDescriptor lroundf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle lroundf$MH = RuntimeHelper.downcallHandle(
        "lroundf",
        constants$29.lroundf$FUNC
    );
    static final FunctionDescriptor nanf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nanf$MH = RuntimeHelper.downcallHandle(
        "nanf",
        constants$29.nanf$FUNC
    );
    static final FunctionDescriptor nearbyintf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle nearbyintf$MH = RuntimeHelper.downcallHandle(
        "nearbyintf",
        constants$29.nearbyintf$FUNC
    );
    static final FunctionDescriptor nextafterf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle nextafterf$MH = RuntimeHelper.downcallHandle(
        "nextafterf",
        constants$29.nextafterf$FUNC
    );
    static final FunctionDescriptor remainderf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle remainderf$MH = RuntimeHelper.downcallHandle(
        "remainderf",
        constants$29.remainderf$FUNC
    );
    static final FunctionDescriptor remquof$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle remquof$MH = RuntimeHelper.downcallHandle(
        "remquof",
        constants$29.remquof$FUNC
    );
}


