// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$176 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$176() {}
    static final FunctionDescriptor avio_wb24$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle avio_wb24$MH = RuntimeHelper.downcallHandle(
        "avio_wb24",
        constants$176.avio_wb24$FUNC
    );
    static final FunctionDescriptor avio_wl16$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle avio_wl16$MH = RuntimeHelper.downcallHandle(
        "avio_wl16",
        constants$176.avio_wl16$FUNC
    );
    static final FunctionDescriptor avio_wb16$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle avio_wb16$MH = RuntimeHelper.downcallHandle(
        "avio_wb16",
        constants$176.avio_wb16$FUNC
    );
    static final FunctionDescriptor avio_put_str$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avio_put_str$MH = RuntimeHelper.downcallHandle(
        "avio_put_str",
        constants$176.avio_put_str$FUNC
    );
    static final FunctionDescriptor avio_put_str16le$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avio_put_str16le$MH = RuntimeHelper.downcallHandle(
        "avio_put_str16le",
        constants$176.avio_put_str16le$FUNC
    );
    static final FunctionDescriptor avio_put_str16be$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avio_put_str16be$MH = RuntimeHelper.downcallHandle(
        "avio_put_str16be",
        constants$176.avio_put_str16be$FUNC
    );
}


