// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$204 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$204() {}
    static final FunctionDescriptor av_pix_fmt_get_chroma_sub_sample$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_pix_fmt_get_chroma_sub_sample$MH = RuntimeHelper.downcallHandle(
        "av_pix_fmt_get_chroma_sub_sample",
        constants$204.av_pix_fmt_get_chroma_sub_sample$FUNC
    );
    static final FunctionDescriptor av_pix_fmt_count_planes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_pix_fmt_count_planes$MH = RuntimeHelper.downcallHandle(
        "av_pix_fmt_count_planes",
        constants$204.av_pix_fmt_count_planes$FUNC
    );
    static final FunctionDescriptor av_color_range_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_color_range_name$MH = RuntimeHelper.downcallHandle(
        "av_color_range_name",
        constants$204.av_color_range_name$FUNC
    );
    static final FunctionDescriptor av_color_range_from_name$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_color_range_from_name$MH = RuntimeHelper.downcallHandle(
        "av_color_range_from_name",
        constants$204.av_color_range_from_name$FUNC
    );
    static final FunctionDescriptor av_color_primaries_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_color_primaries_name$MH = RuntimeHelper.downcallHandle(
        "av_color_primaries_name",
        constants$204.av_color_primaries_name$FUNC
    );
    static final FunctionDescriptor av_color_primaries_from_name$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_color_primaries_from_name$MH = RuntimeHelper.downcallHandle(
        "av_color_primaries_from_name",
        constants$204.av_color_primaries_from_name$FUNC
    );
}


