// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$11 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$11() {}
    static final FunctionDescriptor _dnorm$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _dnorm$MH = RuntimeHelper.downcallHandle(
        "_dnorm",
        constants$11._dnorm$FUNC
    );
    static final FunctionDescriptor _fdnorm$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _fdnorm$MH = RuntimeHelper.downcallHandle(
        "_fdnorm",
        constants$11._fdnorm$FUNC
    );
    static final FunctionDescriptor _dpoly$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _dpoly$MH = RuntimeHelper.downcallHandle(
        "_dpoly",
        constants$11._dpoly$FUNC
    );
    static final FunctionDescriptor _fdpoly$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _fdpoly$MH = RuntimeHelper.downcallHandle(
        "_fdpoly",
        constants$11._fdpoly$FUNC
    );
    static final FunctionDescriptor _dlog$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _dlog$MH = RuntimeHelper.downcallHandle(
        "_dlog",
        constants$11._dlog$FUNC
    );
    static final FunctionDescriptor _fdlog$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _fdlog$MH = RuntimeHelper.downcallHandle(
        "_fdlog",
        constants$11._fdlog$FUNC
    );
}


