// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$154 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$154() {}
    static final FunctionDescriptor av_packet_side_data_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_packet_side_data_name$MH = RuntimeHelper.downcallHandle(
        "av_packet_side_data_name",
        constants$154.av_packet_side_data_name$FUNC
    );
    static final FunctionDescriptor av_packet_pack_dictionary$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_packet_pack_dictionary$MH = RuntimeHelper.downcallHandle(
        "av_packet_pack_dictionary",
        constants$154.av_packet_pack_dictionary$FUNC
    );
    static final FunctionDescriptor av_packet_unpack_dictionary$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_packet_unpack_dictionary$MH = RuntimeHelper.downcallHandle(
        "av_packet_unpack_dictionary",
        constants$154.av_packet_unpack_dictionary$FUNC
    );
    static final FunctionDescriptor av_packet_free_side_data$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_packet_free_side_data$MH = RuntimeHelper.downcallHandle(
        "av_packet_free_side_data",
        constants$154.av_packet_free_side_data$FUNC
    );
    static final FunctionDescriptor av_packet_ref$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_packet_ref$MH = RuntimeHelper.downcallHandle(
        "av_packet_ref",
        constants$154.av_packet_ref$FUNC
    );
    static final FunctionDescriptor av_packet_unref$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_packet_unref$MH = RuntimeHelper.downcallHandle(
        "av_packet_unref",
        constants$154.av_packet_unref$FUNC
    );
}


