// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$142 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$142() {}
    static final FunctionDescriptor av_frame_alloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle av_frame_alloc$MH = RuntimeHelper.downcallHandle(
        "av_frame_alloc",
        constants$142.av_frame_alloc$FUNC
    );
    static final FunctionDescriptor av_frame_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_frame_free$MH = RuntimeHelper.downcallHandle(
        "av_frame_free",
        constants$142.av_frame_free$FUNC
    );
    static final FunctionDescriptor av_frame_ref$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_frame_ref$MH = RuntimeHelper.downcallHandle(
        "av_frame_ref",
        constants$142.av_frame_ref$FUNC
    );
    static final FunctionDescriptor av_frame_clone$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_frame_clone$MH = RuntimeHelper.downcallHandle(
        "av_frame_clone",
        constants$142.av_frame_clone$FUNC
    );
    static final FunctionDescriptor av_frame_unref$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_frame_unref$MH = RuntimeHelper.downcallHandle(
        "av_frame_unref",
        constants$142.av_frame_unref$FUNC
    );
    static final FunctionDescriptor av_frame_move_ref$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_frame_move_ref$MH = RuntimeHelper.downcallHandle(
        "av_frame_move_ref",
        constants$142.av_frame_move_ref$FUNC
    );
}


