// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$122 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$122() {}
    static final FunctionDescriptor av_realloc_array$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle av_realloc_array$MH = RuntimeHelper.downcallHandle(
        "av_realloc_array",
        constants$122.av_realloc_array$FUNC
    );
    static final FunctionDescriptor av_reallocp_array$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle av_reallocp_array$MH = RuntimeHelper.downcallHandle(
        "av_reallocp_array",
        constants$122.av_reallocp_array$FUNC
    );
    static final FunctionDescriptor av_fast_realloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle av_fast_realloc$MH = RuntimeHelper.downcallHandle(
        "av_fast_realloc",
        constants$122.av_fast_realloc$FUNC
    );
    static final FunctionDescriptor av_fast_malloc$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle av_fast_malloc$MH = RuntimeHelper.downcallHandle(
        "av_fast_malloc",
        constants$122.av_fast_malloc$FUNC
    );
    static final FunctionDescriptor av_fast_mallocz$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle av_fast_mallocz$MH = RuntimeHelper.downcallHandle(
        "av_fast_mallocz",
        constants$122.av_fast_mallocz$FUNC
    );
    static final FunctionDescriptor av_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_free$MH = RuntimeHelper.downcallHandle(
        "av_free",
        constants$122.av_free$FUNC
    );
}


