// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$19 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$19() {}
    static final FunctionDescriptor floor$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle floor$MH = RuntimeHelper.downcallHandle(
        "floor",
        constants$19.floor$FUNC
    );
    static final FunctionDescriptor fma$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle fma$MH = RuntimeHelper.downcallHandle(
        "fma",
        constants$19.fma$FUNC
    );
    static final FunctionDescriptor fmax$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle fmax$MH = RuntimeHelper.downcallHandle(
        "fmax",
        constants$19.fmax$FUNC
    );
    static final FunctionDescriptor fmin$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle fmin$MH = RuntimeHelper.downcallHandle(
        "fmin",
        constants$19.fmin$FUNC
    );
    static final FunctionDescriptor frexp$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle frexp$MH = RuntimeHelper.downcallHandle(
        "frexp",
        constants$19.frexp$FUNC
    );
    static final FunctionDescriptor hypot$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle hypot$MH = RuntimeHelper.downcallHandle(
        "hypot",
        constants$19.hypot$FUNC
    );
}


