// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$153 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$153() {}
    static final FunctionDescriptor av_grow_packet$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_grow_packet$MH = RuntimeHelper.downcallHandle(
        "av_grow_packet",
        constants$153.av_grow_packet$FUNC
    );
    static final FunctionDescriptor av_packet_from_data$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_packet_from_data$MH = RuntimeHelper.downcallHandle(
        "av_packet_from_data",
        constants$153.av_packet_from_data$FUNC
    );
    static final FunctionDescriptor av_packet_new_side_data$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle av_packet_new_side_data$MH = RuntimeHelper.downcallHandle(
        "av_packet_new_side_data",
        constants$153.av_packet_new_side_data$FUNC
    );
    static final FunctionDescriptor av_packet_add_side_data$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle av_packet_add_side_data$MH = RuntimeHelper.downcallHandle(
        "av_packet_add_side_data",
        constants$153.av_packet_add_side_data$FUNC
    );
    static final FunctionDescriptor av_packet_shrink_side_data$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle av_packet_shrink_side_data$MH = RuntimeHelper.downcallHandle(
        "av_packet_shrink_side_data",
        constants$153.av_packet_shrink_side_data$FUNC
    );
    static final FunctionDescriptor av_packet_get_side_data$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_packet_get_side_data$MH = RuntimeHelper.downcallHandle(
        "av_packet_get_side_data",
        constants$153.av_packet_get_side_data$FUNC
    );
}


