// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$78 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$78() {}
    static final FunctionDescriptor __sys_nerr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle __sys_nerr$MH = RuntimeHelper.downcallHandle(
        "__sys_nerr",
        constants$78.__sys_nerr$FUNC
    );
    static final FunctionDescriptor __p__pgmptr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle __p__pgmptr$MH = RuntimeHelper.downcallHandle(
        "__p__pgmptr",
        constants$78.__p__pgmptr$FUNC
    );
    static final FunctionDescriptor __p__wpgmptr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle __p__wpgmptr$MH = RuntimeHelper.downcallHandle(
        "__p__wpgmptr",
        constants$78.__p__wpgmptr$FUNC
    );
    static final FunctionDescriptor __p__fmode$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle __p__fmode$MH = RuntimeHelper.downcallHandle(
        "__p__fmode",
        constants$78.__p__fmode$FUNC
    );
    static final FunctionDescriptor _get_pgmptr$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _get_pgmptr$MH = RuntimeHelper.downcallHandle(
        "_get_pgmptr",
        constants$78._get_pgmptr$FUNC
    );
    static final FunctionDescriptor _get_wpgmptr$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _get_wpgmptr$MH = RuntimeHelper.downcallHandle(
        "_get_wpgmptr",
        constants$78._get_wpgmptr$FUNC
    );
}


