// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$27 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$27() {}
    static final FunctionDescriptor fmaf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle fmaf$MH = RuntimeHelper.downcallHandle(
        "fmaf",
        constants$27.fmaf$FUNC
    );
    static final FunctionDescriptor fmaxf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle fmaxf$MH = RuntimeHelper.downcallHandle(
        "fmaxf",
        constants$27.fmaxf$FUNC
    );
    static final FunctionDescriptor fminf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle fminf$MH = RuntimeHelper.downcallHandle(
        "fminf",
        constants$27.fminf$FUNC
    );
    static final FunctionDescriptor _hypotf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle _hypotf$MH = RuntimeHelper.downcallHandle(
        "_hypotf",
        constants$27._hypotf$FUNC
    );
    static final FunctionDescriptor ilogbf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle ilogbf$MH = RuntimeHelper.downcallHandle(
        "ilogbf",
        constants$27.ilogbf$FUNC
    );
    static final FunctionDescriptor lgammaf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle lgammaf$MH = RuntimeHelper.downcallHandle(
        "lgammaf",
        constants$27.lgammaf$FUNC
    );
}


