// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$129 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$129() {}
    static final FunctionDescriptor av_log_set_callback$callback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_log_set_callback$callback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$129.av_log_set_callback$callback_DOWN$FUNC
    );
    static final FunctionDescriptor av_log_set_callback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_log_set_callback$MH = RuntimeHelper.downcallHandle(
        "av_log_set_callback",
        constants$129.av_log_set_callback$FUNC
    );
    static final FunctionDescriptor av_log_default_callback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_log_default_callback$MH = RuntimeHelper.downcallHandle(
        "av_log_default_callback",
        constants$129.av_log_default_callback$FUNC
    );
    static final FunctionDescriptor av_default_item_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_default_item_name$MH = RuntimeHelper.downcallHandle(
        "av_default_item_name",
        constants$129.av_default_item_name$FUNC
    );
    static final FunctionDescriptor av_default_get_category$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_default_get_category$MH = RuntimeHelper.downcallHandle(
        "av_default_get_category",
        constants$129.av_default_get_category$FUNC
    );
    static final FunctionDescriptor av_log_format_line$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_log_format_line$MH = RuntimeHelper.downcallHandle(
        "av_log_format_line",
        constants$129.av_log_format_line$FUNC
    );
}


