// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$191 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$191() {}
    static final FunctionDescriptor avformat_write_header$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avformat_write_header$MH = RuntimeHelper.downcallHandle(
        "avformat_write_header",
        constants$191.avformat_write_header$FUNC
    );
    static final FunctionDescriptor avformat_init_output$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avformat_init_output$MH = RuntimeHelper.downcallHandle(
        "avformat_init_output",
        constants$191.avformat_init_output$FUNC
    );
    static final FunctionDescriptor av_write_frame$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_write_frame$MH = RuntimeHelper.downcallHandle(
        "av_write_frame",
        constants$191.av_write_frame$FUNC
    );
    static final FunctionDescriptor av_interleaved_write_frame$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_interleaved_write_frame$MH = RuntimeHelper.downcallHandle(
        "av_interleaved_write_frame",
        constants$191.av_interleaved_write_frame$FUNC
    );
    static final FunctionDescriptor av_write_uncoded_frame$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_write_uncoded_frame$MH = RuntimeHelper.downcallHandle(
        "av_write_uncoded_frame",
        constants$191.av_write_uncoded_frame$FUNC
    );
    static final FunctionDescriptor av_interleaved_write_uncoded_frame$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_interleaved_write_uncoded_frame$MH = RuntimeHelper.downcallHandle(
        "av_interleaved_write_uncoded_frame",
        constants$191.av_interleaved_write_uncoded_frame$FUNC
    );
}


