// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$89 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$89() {}
    static final FunctionDescriptor _fcvt$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _fcvt$MH = RuntimeHelper.downcallHandle(
        "_fcvt",
        constants$89._fcvt$FUNC
    );
    static final FunctionDescriptor _gcvt_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _gcvt_s$MH = RuntimeHelper.downcallHandle(
        "_gcvt_s",
        constants$89._gcvt_s$FUNC
    );
    static final FunctionDescriptor _gcvt$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _gcvt$MH = RuntimeHelper.downcallHandle(
        "_gcvt",
        constants$89._gcvt$FUNC
    );
    static final FunctionDescriptor ___mb_cur_max_func$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle ___mb_cur_max_func$MH = RuntimeHelper.downcallHandle(
        "___mb_cur_max_func",
        constants$89.___mb_cur_max_func$FUNC
    );
    static final FunctionDescriptor ___mb_cur_max_l_func$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ___mb_cur_max_l_func$MH = RuntimeHelper.downcallHandle(
        "___mb_cur_max_l_func",
        constants$89.___mb_cur_max_l_func$FUNC
    );
    static final FunctionDescriptor mblen$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle mblen$MH = RuntimeHelper.downcallHandle(
        "mblen",
        constants$89.mblen$FUNC
    );
}


