// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$107 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$107() {}
    static final FunctionDescriptor _wcsupr_l$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcsupr_l$MH = RuntimeHelper.downcallHandle(
        "_wcsupr_l",
        constants$107._wcsupr_l$FUNC
    );
    static final FunctionDescriptor wcsxfrm$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle wcsxfrm$MH = RuntimeHelper.downcallHandle(
        "wcsxfrm",
        constants$107.wcsxfrm$FUNC
    );
    static final FunctionDescriptor _wcsxfrm_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcsxfrm_l$MH = RuntimeHelper.downcallHandle(
        "_wcsxfrm_l",
        constants$107._wcsxfrm_l$FUNC
    );
    static final FunctionDescriptor wcscoll$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle wcscoll$MH = RuntimeHelper.downcallHandle(
        "wcscoll",
        constants$107.wcscoll$FUNC
    );
    static final FunctionDescriptor _wcscoll_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcscoll_l$MH = RuntimeHelper.downcallHandle(
        "_wcscoll_l",
        constants$107._wcscoll_l$FUNC
    );
    static final FunctionDescriptor _wcsicoll$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcsicoll$MH = RuntimeHelper.downcallHandle(
        "_wcsicoll",
        constants$107._wcsicoll$FUNC
    );
}


