// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$125 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$125() {}
    static final FunctionDescriptor av_mul_q$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("num"),
        Constants$root.C_LONG$LAYOUT.withName("den")
    ).withName("AVRational"),
        MemoryLayout.structLayout(
            Constants$root.C_LONG$LAYOUT.withName("num"),
            Constants$root.C_LONG$LAYOUT.withName("den")
        ).withName("AVRational"),
        MemoryLayout.structLayout(
            Constants$root.C_LONG$LAYOUT.withName("num"),
            Constants$root.C_LONG$LAYOUT.withName("den")
        ).withName("AVRational")
    );
    static final MethodHandle av_mul_q$MH = RuntimeHelper.downcallHandle(
        "av_mul_q",
        constants$125.av_mul_q$FUNC
    );
    static final FunctionDescriptor av_div_q$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("num"),
        Constants$root.C_LONG$LAYOUT.withName("den")
    ).withName("AVRational"),
        MemoryLayout.structLayout(
            Constants$root.C_LONG$LAYOUT.withName("num"),
            Constants$root.C_LONG$LAYOUT.withName("den")
        ).withName("AVRational"),
        MemoryLayout.structLayout(
            Constants$root.C_LONG$LAYOUT.withName("num"),
            Constants$root.C_LONG$LAYOUT.withName("den")
        ).withName("AVRational")
    );
    static final MethodHandle av_div_q$MH = RuntimeHelper.downcallHandle(
        "av_div_q",
        constants$125.av_div_q$FUNC
    );
    static final FunctionDescriptor av_add_q$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("num"),
        Constants$root.C_LONG$LAYOUT.withName("den")
    ).withName("AVRational"),
        MemoryLayout.structLayout(
            Constants$root.C_LONG$LAYOUT.withName("num"),
            Constants$root.C_LONG$LAYOUT.withName("den")
        ).withName("AVRational"),
        MemoryLayout.structLayout(
            Constants$root.C_LONG$LAYOUT.withName("num"),
            Constants$root.C_LONG$LAYOUT.withName("den")
        ).withName("AVRational")
    );
    static final MethodHandle av_add_q$MH = RuntimeHelper.downcallHandle(
        "av_add_q",
        constants$125.av_add_q$FUNC
    );
    static final FunctionDescriptor av_sub_q$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("num"),
        Constants$root.C_LONG$LAYOUT.withName("den")
    ).withName("AVRational"),
        MemoryLayout.structLayout(
            Constants$root.C_LONG$LAYOUT.withName("num"),
            Constants$root.C_LONG$LAYOUT.withName("den")
        ).withName("AVRational"),
        MemoryLayout.structLayout(
            Constants$root.C_LONG$LAYOUT.withName("num"),
            Constants$root.C_LONG$LAYOUT.withName("den")
        ).withName("AVRational")
    );
    static final MethodHandle av_sub_q$MH = RuntimeHelper.downcallHandle(
        "av_sub_q",
        constants$125.av_sub_q$FUNC
    );
    static final FunctionDescriptor av_d2q$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("num"),
        Constants$root.C_LONG$LAYOUT.withName("den")
    ).withName("AVRational"),
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_d2q$MH = RuntimeHelper.downcallHandle(
        "av_d2q",
        constants$125.av_d2q$FUNC
    );
    static final FunctionDescriptor av_nearer_q$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_LONG$LAYOUT.withName("num"),
            Constants$root.C_LONG$LAYOUT.withName("den")
        ).withName("AVRational"),
        MemoryLayout.structLayout(
            Constants$root.C_LONG$LAYOUT.withName("num"),
            Constants$root.C_LONG$LAYOUT.withName("den")
        ).withName("AVRational"),
        MemoryLayout.structLayout(
            Constants$root.C_LONG$LAYOUT.withName("num"),
            Constants$root.C_LONG$LAYOUT.withName("den")
        ).withName("AVRational")
    );
    static final MethodHandle av_nearer_q$MH = RuntimeHelper.downcallHandle(
        "av_nearer_q",
        constants$125.av_nearer_q$FUNC
    );
}


