// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$207 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$207() {}
    static final FunctionDescriptor av_read_image_line$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_read_image_line$MH = RuntimeHelper.downcallHandle(
        "av_read_image_line",
        constants$207.av_read_image_line$FUNC
    );
    static final FunctionDescriptor av_write_image_line2$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_write_image_line2$MH = RuntimeHelper.downcallHandle(
        "av_write_image_line2",
        constants$207.av_write_image_line2$FUNC
    );
    static final FunctionDescriptor av_write_image_line$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_write_image_line$MH = RuntimeHelper.downcallHandle(
        "av_write_image_line",
        constants$207.av_write_image_line$FUNC
    );
    static final FunctionDescriptor av_pix_fmt_swap_endianness$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_pix_fmt_swap_endianness$MH = RuntimeHelper.downcallHandle(
        "av_pix_fmt_swap_endianness",
        constants$207.av_pix_fmt_swap_endianness$FUNC
    );
    static final FunctionDescriptor av_get_pix_fmt_loss$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_get_pix_fmt_loss$MH = RuntimeHelper.downcallHandle(
        "av_get_pix_fmt_loss",
        constants$207.av_get_pix_fmt_loss$FUNC
    );
    static final FunctionDescriptor av_find_best_pix_fmt_of_2$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_find_best_pix_fmt_of_2$MH = RuntimeHelper.downcallHandle(
        "av_find_best_pix_fmt_of_2",
        constants$207.av_find_best_pix_fmt_of_2$FUNC
    );
}


