// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$150 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$150() {}
    static final FunctionDescriptor av_codec_is_decoder$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_codec_is_decoder$MH = RuntimeHelper.downcallHandle(
        "av_codec_is_decoder",
        constants$150.av_codec_is_decoder$FUNC
    );
    static final FunctionDescriptor av_get_profile_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_get_profile_name$MH = RuntimeHelper.downcallHandle(
        "av_get_profile_name",
        constants$150.av_get_profile_name$FUNC
    );
    static final FunctionDescriptor avcodec_get_hw_config$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle avcodec_get_hw_config$MH = RuntimeHelper.downcallHandle(
        "avcodec_get_hw_config",
        constants$150.avcodec_get_hw_config$FUNC
    );
    static final FunctionDescriptor avcodec_descriptor_get$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle avcodec_descriptor_get$MH = RuntimeHelper.downcallHandle(
        "avcodec_descriptor_get",
        constants$150.avcodec_descriptor_get$FUNC
    );
    static final FunctionDescriptor avcodec_descriptor_next$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avcodec_descriptor_next$MH = RuntimeHelper.downcallHandle(
        "avcodec_descriptor_next",
        constants$150.avcodec_descriptor_next$FUNC
    );
    static final FunctionDescriptor avcodec_descriptor_get_by_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle avcodec_descriptor_get_by_name$MH = RuntimeHelper.downcallHandle(
        "avcodec_descriptor_get_by_name",
        constants$150.avcodec_descriptor_get_by_name$FUNC
    );
}


