// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$90 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$90() {}
    static final FunctionDescriptor _mblen_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mblen_l$MH = RuntimeHelper.downcallHandle(
        "_mblen_l",
        constants$90._mblen_l$FUNC
    );
    static final FunctionDescriptor _mbstrlen$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mbstrlen$MH = RuntimeHelper.downcallHandle(
        "_mbstrlen",
        constants$90._mbstrlen$FUNC
    );
    static final FunctionDescriptor _mbstrlen_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mbstrlen_l$MH = RuntimeHelper.downcallHandle(
        "_mbstrlen_l",
        constants$90._mbstrlen_l$FUNC
    );
    static final FunctionDescriptor _mbstrnlen$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _mbstrnlen$MH = RuntimeHelper.downcallHandle(
        "_mbstrnlen",
        constants$90._mbstrnlen$FUNC
    );
    static final FunctionDescriptor _mbstrnlen_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _mbstrnlen_l$MH = RuntimeHelper.downcallHandle(
        "_mbstrnlen_l",
        constants$90._mbstrnlen_l$FUNC
    );
    static final FunctionDescriptor mbtowc$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle mbtowc$MH = RuntimeHelper.downcallHandle(
        "mbtowc",
        constants$90.mbtowc$FUNC
    );
}


