// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$203 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$203() {}
    static final FunctionDescriptor sws_get_class$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle sws_get_class$MH = RuntimeHelper.downcallHandle(
        "sws_get_class",
        constants$203.sws_get_class$FUNC
    );
    static final FunctionDescriptor av_get_bits_per_pixel$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_get_bits_per_pixel$MH = RuntimeHelper.downcallHandle(
        "av_get_bits_per_pixel",
        constants$203.av_get_bits_per_pixel$FUNC
    );
    static final FunctionDescriptor av_get_padded_bits_per_pixel$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_get_padded_bits_per_pixel$MH = RuntimeHelper.downcallHandle(
        "av_get_padded_bits_per_pixel",
        constants$203.av_get_padded_bits_per_pixel$FUNC
    );
    static final FunctionDescriptor av_pix_fmt_desc_get$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle av_pix_fmt_desc_get$MH = RuntimeHelper.downcallHandle(
        "av_pix_fmt_desc_get",
        constants$203.av_pix_fmt_desc_get$FUNC
    );
    static final FunctionDescriptor av_pix_fmt_desc_next$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_pix_fmt_desc_next$MH = RuntimeHelper.downcallHandle(
        "av_pix_fmt_desc_next",
        constants$203.av_pix_fmt_desc_next$FUNC
    );
    static final FunctionDescriptor av_pix_fmt_desc_get_id$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle av_pix_fmt_desc_get_id$MH = RuntimeHelper.downcallHandle(
        "av_pix_fmt_desc_get_id",
        constants$203.av_pix_fmt_desc_get_id$FUNC
    );
}


