// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$7 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$7() {}
    static final FunctionDescriptor wcstoumax$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle wcstoumax$MH = RuntimeHelper.downcallHandle(
        "wcstoumax",
        constants$7.wcstoumax$FUNC
    );
    static final FunctionDescriptor _wcstoumax_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcstoumax_l$MH = RuntimeHelper.downcallHandle(
        "_wcstoumax_l",
        constants$7._wcstoumax_l$FUNC
    );
    static final OfDouble _HUGE$LAYOUT = Constants$root.C_DOUBLE$LAYOUT;
    static final VarHandle _HUGE$VH = constants$7._HUGE$LAYOUT.varHandle();
    static final MemorySegment _HUGE$SEGMENT = RuntimeHelper.lookupGlobalVariable("_HUGE", constants$7._HUGE$LAYOUT);
    static final FunctionDescriptor _fperrraise$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _fperrraise$MH = RuntimeHelper.downcallHandle(
        "_fperrraise",
        constants$7._fperrraise$FUNC
    );
    static final FunctionDescriptor _dclass$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle _dclass$MH = RuntimeHelper.downcallHandle(
        "_dclass",
        constants$7._dclass$FUNC
    );
    static final FunctionDescriptor _fdclass$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle _fdclass$MH = RuntimeHelper.downcallHandle(
        "_fdclass",
        constants$7._fdclass$FUNC
    );
}


