// Generated by jextract

package com.icuxika.jextract.libffmpeg;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _lldiv_t lldiv_t;
 * }
 */
public final class lldiv_t extends _lldiv_t$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private lldiv_t() {}
}


